title: Marcelo Andrade
description: Technology with something to say

url: http://marceloandrade.info
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Archive
   url: /archive
 - title: Portifolio
   url: /portifolio

social:
   github: mfandrade
   twitter: mfandrade
   facebook: mfandrade1
   email: mfandrade@gmail.com

google_analytics: "UA-58417175-1"
disqus_comments: mfandrade
